version: '2'
services:
  app:
    image: nlesc/xenon-hdfs-kerberos:latest
    container_name: xenon-hdfs-kerberos
    ports:
      - 88:88/tcp
      - 88:88/udp
      - 8020:8020
      - 50010:50010
      - 50470:50470
      - 50475:50475
    restart: on-failure